type Message {
  message: String!
  username: String
}

type Connection {
  username: String!
  connected: Boolean!
}

type Query {
  messages: [Message]
}

input InputData {
  inputValue: String
}

input ConnectionData {
  username: String!
  connected: Boolean!
}

type Mutation {
  sendMessage(input: InputData): Boolean
  connectionUpdate(connection: ConnectionData): Boolean
}

type Subscription {
  messageAdded: Message
  connectionMessage: Connection
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
