type Message {
  message: String
  username: String
}

type Query {
  messages: [Message]
}

input InputData {
  inputValue: String
}

type Mutation {
  sendMessage(input: InputData): Boolean
}

type Subscription {
  messageAdded: Message
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
